# Generated by Django 2.2.10 on 2020-03-01 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Recepi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('preparation', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'recepi',
            },
        ),
        migrations.CreateModel(
            name='RecepiCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'recepi_categories',
            },
        ),
        migrations.CreateModel(
            name='RecepiFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Recepi')),
            ],
            options={
                'db_table': 'recepi_follower',
            },
        ),
    ]
