# Generated by Django 2.2.12 on 2020-07-12 13:23

import backend.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'category',
            },
            bases=(backend.utils.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recepi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('preparation', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'recepi',
            },
        ),
        migrations.CreateModel(
            name='RecepiCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Category')),
                ('recepi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recepi')),
            ],
            options={
                'db_table': 'recepi_categories',
                'unique_together': {('recepi', 'category')},
            },
        ),
        migrations.AddField(
            model_name='recepi',
            name='categories',
            field=models.ManyToManyField(through='core.RecepiCategories', to='core.Category'),
        ),
        migrations.AddField(
            model_name='recepi',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecepiFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Recepi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recepi_follower',
                'unique_together': {('recepi', 'user')},
            },
        ),
    ]
